# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Anders Nilsson"
subtitle: "See the world through my eyes!"
author: "Ram Patra"
header:
 title: "Anders"
 subtitle: "Nilsson"
footer:
 name: "Hej! Jag heter Anders!"
 bio: "Jag pluggar till Civilingenjör med inriktning i design i Linköping och har ett nyfunnet intresse för fotografi"
 github: "Letar ni en fotograf för er verksamhet så släng iväg ett mail eller ett PM på Instagram! Jag är öppen för det mesta!"
web_design: "AJ"
social_urls:
  /
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  /
  instagram: "https://www.instagram.com/andersfotograferar/"
  linkedin: "www.linkedin.com/in/andersnilsson98"
  /
  dribbble: "https://dribbble.com/rampatra"
  github: "https://www.github.com/rampatra"
  /
